name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ravikantchauhan/ubuntu22.4-php8.2-fpm:latest

    - name: Push the Docker image to Docker Hub
      run: |
       docker login -u ravikantchauhan -p {{ secrets.DOH }}

       docker push ravikantchauhan/ubuntu22.4-php8.2-fpm:latest
