name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ravikantchauhan --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ravikantchauhan/ubuntu22.4-php8.2-fpm:latest

    - name: Push the Docker image to Docker Hub
      run: docker push ravikantchauhan/ubuntu22.4-php8.2-fpm:latest
