name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Debug - Print Username
      run: echo "${{ secrets.DOCKERHUB_USERNAME }}"

    - name: Log in to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Debug - Print Username
      run: echo "${{ secrets.DOCKERHUB_USERNAME }}"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ravikantchauhan/ubuntu22.4-php8.2-fpm:latest

    - name: Push the Docker image to Docker Hub
      run: docker push ravikantchauhan/ubuntu22.4-php8.2-fpm:latest
